# Generated by Django 5.2.15 on 2026-06-07 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(upload_to='generated-images/')),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('style', models.CharField(blank=True, max_length=40)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('favorite', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geração',
                'verbose_name_plural': 'Gerações',
                'indexes': [models.Index(fields=['user', '-created_at'], name='generations_user_id_800a84_idx')],
            },
        ),
    ]
