# Generated by Django 5.2.15 on 2026-06-07 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PJ Mídia', max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('colors', models.JSONField(default=list)),
                ('default_phrase', models.CharField(blank=True, max_length=240)),
                ('button_text', models.CharField(blank=True, max_length=60)),
                ('signature', models.CharField(blank=True, max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand-logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
