# Generated by Django 5.2.15 on 2026-06-07 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(default='outros', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-images/')),
                ('off_image_url', models.URLField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(choices=[('user', 'user'), ('openfoodfacts', 'openfoodfacts')], default='user', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'indexes': [models.Index(fields=['user', 'name'], name='products_pr_user_id_e25acc_idx'), models.Index(fields=['user', '-created_at'], name='products_pr_user_id_2803d1_idx')],
            },
        ),
    ]
